{
 "title": "Device SSL",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(f5_system_info, environment)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "device_name",
    "label": "Device",
    "query": {
     "query": "label_values(f5_system_state_up_ratio{environment=~\"$environment\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "NetHSM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Async Queue Done Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(f5_nethsm_async_queue_done_total{environment=~\"$environment\", job=\"$device_name\"}[$__rate_interval])",
     "legendFormat": "Queue: {{f5_nethsm_queue}}"
    }
   ]
  },
  {
   "title": "Async Queue Current Queued",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "f5_nethsm_async_queue_queued{environment=~\"$environment\", job=\"$device_name\"}",
     "legendFormat": "Queue: {{f5_nethsm_queue}}"
    }
   ]
  },
  {
   "title": "Async Queue Avg. Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "f5_nethsm_async_queue_queue_time_avg_microseconds{environment=~\"$environment\", job=\"$device_name\"}",
     "legendFormat": "Queue: {{f5_nethsm_queue}}"
    }
   ]
  },
  {
   "title": "PKCS11d Operations Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(f5_nethsm_pkcs11d_operations_total{environment=~\"$environment\", job=\"$device_name\"}[$__rate_interval])",
     "legendFormat": "Thread: {{f5_nethsm_thread}} - {{operation}}"
    }
   ]
  },
  {
   "title": "PKCS11d Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(f5_nethsm_pkcs11d_operation_errors_total{environment=~\"$environment\", job=\"$device_name\"}[$__rate_interval])",
     "legendFormat": "Thread: {{f5_nethsm_thread}} - {{operation}}"
    }
   ]
  },
  { "title": "Client SSL Profile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Client SSL Profile Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "f5_profile_client_ssl_info{environment=~\"$environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client SSL Connection Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(f5_profile_client_ssl_connections_total{environment=~\"$environment\", job=\"$device_name\"}[$__rate_interval])",
     "legendFormat": "{{f5_profile_client_ssl_name}}"
    }
   ]
  },
  {
   "title": "Client SSL Ciphers Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "rate(f5_profile_client_ssl_cipher_uses_total{environment=~\"$environment\", job=\"$device_name\"}[$__rate_interval])",
     "legendFormat": "{{f5_profile_client_ssl_name}} - {{f5_profile_client_ssl_ciphers}}"
    }
   ]
  },
  {
   "title": "Client SSL Handshakes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "rate(f5_profile_client_ssl_secure_handshakes_total{environment=~\"$environment\", job=\"$device_name\"}[$__rate_interval])",
     "legendFormat": "{{f5_profile_client_ssl_name}}"
    }
   ]
  },
  { "title": "Server SSL Profile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Server SSL Profile Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "f5_profile_server_ssl_info{environment=~\"$environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server SSL Connection Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(f5_profile_server_ssl_connections_total{environment=~\"$environment\", job=\"$device_name\"}[$__rate_interval])",
     "legendFormat": "{{f5_profile_server_ssl_name}}"
    }
   ]
  },
  {
   "title": "Server SSL Ciphers Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "rate(f5_profile_server_ssl_cipher_uses_total{environment=~\"$environment\", job=\"$device_name\"}[$__rate_interval])",
     "legendFormat": "{{f5_profile_server_ssl_name}} - {{f5_profile_server_ssl_ciphers}}"
    }
   ]
  },
  {
   "title": "Server SSL Handshakes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "rate(f5_profile_server_ssl_secure_handshakes_total{environment=~\"$environment\", job=\"$device_name\"}[$__rate_interval])",
     "legendFormat": "{{f5_profile_server_ssl_name}}"
    }
   ]
  }
 ]
}