{
 "title": "Device WAF Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(f5_system_info, environment)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "device_name",
    "label": "Device",
    "query": {
     "query": "label_values(f5_system_state_up_ratio{environment=~\"$environment\"},job)"
    }
   },
   {
    "name": "asm_policy",
    "label": "Policy",
    "query": {
     "query": "label_values(f5_policy_asm_info,f5_policy_asm_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "WAF Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "WAF Event Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(f5_policy_asm_incidents_total{environment=~\"$environment\", job=\"$device_name\"}[$__rate_interval])",
     "legendFormat": "Incidents"
    },
    {
     "expr": "rate(f5_policy_asm_bot_events_total{environment=~\"$environment\", job=\"$device_name\"}[$__rate_interval])",
     "legendFormat": "Bot Events"
    },
    {
     "expr": "rate(f5_policy_asm_bot_incidents_total{environment=~\"$environment\", job=\"$device_name\"}[$__rate_interval])",
     "legendFormat": "Bot Incidents"
    },
    {
     "expr": "rate(f5_policy_asm_brute_force_attacks_total{environment=~\"$environment\", job=\"$device_name\"}[$__rate_interval])",
     "legendFormat": "Brute Force Attacks"
    }
   ]
  },
  {
   "title": "Incidents [1h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(f5_policy_asm_incidents_total{environment=~\"$environment\", job=\"$device_name\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bot Events [1h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(f5_policy_asm_bot_events_total{environment=~\"$environment\", job=\"$device_name\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bot Incidents [1h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(f5_policy_asm_bot_incidents_total{environment=~\"$environment\", job=\"$device_name\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Brute Force Attacks [1h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(f5_policy_asm_brute_force_attacks_total{environment=~\"$environment\", job=\"$device_name\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incidents [24h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(f5_policy_asm_incidents_total{environment=~\"$environment\", job=\"$device_name\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bot Events [24h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(f5_policy_asm_bot_events_total{environment=~\"$environment\", job=\"$device_name\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bot Incidents [24h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(f5_policy_asm_bot_incidents_total{environment=~\"$environment\", job=\"$device_name\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Brute Force Attacks [24h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(f5_policy_asm_brute_force_attacks_total{environment=~\"$environment\", job=\"$device_name\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ASM Policy Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "WAF Feature Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sort_desc(f5_policy_asm_feature_enabled_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_policy_asm_name=~\"$asm_policy\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Applied Virtual Servers",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 5, "y": 12 },
   "targets": [
    {
     "expr": "f5_virtual_server_profile_info{environment=~\"$environment\", job=\"$device_name\", f5_profile_name=~\"$asm_policy\", f5_profile_family=\"asm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signature Set Count By State",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 11, "y": 12 },
   "targets": [
    {
     "expr": "f5_policy_asm_signature_sets_state_count{environment=~\"$environment\", job=\"$device_name\", f5_policy_asm_name=~\"$asm_policy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signature Set Count",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "f5_policy_asm_signature_set_count{environment=~\"$environment\", job=\"$device_name\", f5_policy_asm_name=~\"$asm_policy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Parameter Checking Count",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 12 },
   "targets": [
    {
     "expr": "f5_policy_asm_param_checking_count{environment=~\"$environment\", job=\"$device_name\", f5_policy_asm_name=~\"$asm_policy\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}