{
 "title": "Device Pools",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(f5_system_info, environment)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "device_name",
    "query": {
     "query": "label_values(f5_system_state_up_ratio{environment=~\"$environment\"},job)"
    }
   },
   {
    "name": "pool",
    "query": {
     "query": "label_values(f5_pool_info{job=\"$device_name\"},f5_pool_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "f5_pool_info{environment=~\"$environment\", job=\"$device_name\", f5_pool_name=~\"$pool\"}==1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generation Changes [24h]",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "changes(f5_pool_generation{environment=~\"$environment\", f5_pool_name=~\"$pool\", job=\"$device_name\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pool Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Pool State isAvailable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(f5_pool_availability_ratio{environment=~\"$environment\", job=\"$device_name\", availability_state=\"available\", f5_pool_name=~\"$pool\"}[$__interval])",
     "legendFormat": "{{f5_pool_name}}"
    }
   ]
  },
  {
   "title": "Active Pool Members",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(f5_pool_member_count{environment=~\"$environment\", f5_pool_name=~\"$pool\", job=\"$device_name\", active_state=\"active\"}) by (f5_pool_name, job) / sum(f5_pool_member_count{environment=~\"$environment\", f5_pool_name=~\"$pool\", job=\"$device_name\"}) by (f5_pool_name, job)",
     "legendFormat": "{{f5_pool_name}}"
    }
   ]
  },
  {
   "title": "Pool Availability [24h]",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum_over_time(f5_pool_availability_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_pool_name=~\"$pool\", availability_state=\"available\"}[24h]) / count_over_time(f5_pool_availability_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_pool_name=~\"$pool\", availability_state=\"available\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(f5_pool_availability_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_pool_name=~\"$pool\", availability_state=\"offline\"}[24h]) / count_over_time(f5_pool_availability_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_pool_name=~\"$pool\", availability_state=\"offline\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(f5_pool_availability_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_pool_name=~\"$pool\", availability_state=\"unknown\"}[24h]) / count_over_time(f5_pool_availability_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_pool_name=~\"$pool\", availability_state=\"unknown\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pool Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Pool Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(f5_pool_bytes_in_total{environment=~\"$environment\", job=\"$device_name\", f5_pool_name=~\"$pool\"}[$__rate_interval]) * 8",
     "legendFormat": "{{f5_pool_name}} - In"
    },
    {
     "expr": "rate(f5_pool_bytes_out_total{environment=~\"$environment\", job=\"$device_name\", f5_pool_name=~\"$pool\"}[$__rate_interval]) * -8",
     "legendFormat": "{{f5_pool_name}} - Out"
    }
   ]
  },
  {
   "title": "Active Pool Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "f5_pool_connection_count{environment=~\"$environment\", job=\"$device_name\", f5_pool_name=~\"$pool\"}",
     "legendFormat": "{{f5_pool_name}}"
    }
   ]
  },
  {
   "title": "Pool Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(f5_pool_requests_total{environment=~\"$environment\", f5_pool_name=~\"$pool\", job=\"$device_name\"}[$__rate_interval])",
     "legendFormat": "{{f5_pool_name}}"
    }
   ]
  },
  { "title": "Pool Member Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Pool Member State isAvailable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(f5_pool_member_availability_ratio{environment=~\"$environment\", job=\"$device_name\", availability_state=\"available\", f5_pool_name=~\"$pool\"}[$__interval])",
     "legendFormat": "Pool: {{f5_pool_name}} Member: {{f5_pool_member_name}}"
    }
   ]
  },
  {
   "title": "Pool Member Availability [24h]",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum_over_time(f5_pool_member_availability_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_pool_name=~\"$pool\", availability_state=\"available\"}[24h]) / count_over_time(f5_pool_member_availability_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_pool_name=~\"$pool\", availability_state=\"available\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(f5_pool_member_availability_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_pool_name=~\"$pool\", availability_state=\"offline\"}[24h]) / count_over_time(f5_pool_member_availability_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_pool_name=~\"$pool\", availability_state=\"offline\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(f5_pool_member_availability_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_pool_name=~\"$pool\", availability_state=\"unknown\"}[24h]) / count_over_time(f5_pool_member_availability_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_pool_name=~\"$pool\", availability_state=\"unknown\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pool Member Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Pool Member Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(f5_pool_member_bytes_in_total{environment=~\"$environment\", job=\"$device_name\", f5_pool_name=~\"$pool\"}[$__rate_interval]) * 8",
     "legendFormat": "{{f5_pool_member_name}} - In"
    },
    {
     "expr": "rate(f5_pool_member_bytes_out_total{environment=~\"$environment\", job=\"$device_name\", f5_pool_name=~\"$pool\"}[$__rate_interval]) * -8",
     "legendFormat": "{{f5_pool_member_name}} - Out"
    }
   ]
  },
  {
   "title": "Active Pool Member Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "f5_pool_member_connection_count{environment=~\"$environment\", job=\"$device_name\", f5_pool_name=~\"$pool\"}",
     "legendFormat": "{{f5_pool_member_name}}"
    }
   ]
  },
  {
   "title": "Pool Member Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(f5_pool_member_requests_total{environment=~\"$environment\", f5_pool_name=~\"$pool\", job=\"$device_name\"}[$__rate_interval])",
     "legendFormat": "{{f5_pool_member_name}}"
    }
   ]
  }
 ]
}