{
 "title": "Device Virtual Servers",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device_name",
    "query": {
     "query": "label_values(f5_system_state_up_ratio,job)"
    }
   },
   {
    "name": "virtual_server",
    "query": {
     "query": "label_values(f5_virtual_server_enabled_ratio{job=\"$device_name\"},f5_virtual_server_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VS Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "f5_virtual_server_info{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}==1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generation Changes [24h]",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "changes(f5_virtual_server_generation{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Virtual Server State isAvailable",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(f5_virtual_server_availability_ratio{job=\"$device_name\", availability_state=\"available\", f5_virtual_server_name=~\"$virtual_server\"}[$__interval])",
     "legendFormat": "{{f5_virtual_server_name}}"
    }
   ]
  },
  {
   "title": "Virtual Server isEnabled",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(f5_virtual_server_enabled_ratio{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[$__interval])",
     "legendFormat": "{{f5_virtual_server_name}}"
    }
   ]
  },
  {
   "title": "Virtual Server Availability [24h]",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum_over_time(f5_virtual_server_availability_ratio{job=~\"$device_name\", availability_state=\"available\", f5_virtual_server_name=~\"$virtual_server\"}[24h]) / count_over_time(f5_virtual_server_availability_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"available\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(f5_virtual_server_availability_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"offline\"}[24h]) / count_over_time(f5_virtual_server_availability_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"offline\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(f5_virtual_server_availability_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"unknown\"}[24h]) / count_over_time(f5_virtual_server_availability_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"unknown\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(f5_virtual_server_enabled_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[24h]) / count_over_time(f5_virtual_server_enabled_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Configured Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Virtual Server Pool State",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "f5_virtual_server_info{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", f5_pool_name!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "f5_pool_availability_ratio{job=\"$device_name\"}==1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Applied iRules",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "f5_virtual_server_rule_enabled_ratio{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Applied Profiles",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "f5_virtual_server_profile_info{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "f5_virtual_server_profile_info{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", f5_profile_type=\"http\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Virtual Server CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "f5_virtual_server_cpu_utilization_5s{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}",
     "legendFormat": "{{f5_virtual_server_name}}"
    }
   ]
  },
  {
   "title": "Virtual Server ASM CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "f5_virtual_server_asm_cpu_utilization_percent{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}",
     "legendFormat": "{{f5_virtual_server_name}}"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Virtual Server Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(f5_virtual_server_requests_total{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval])",
     "legendFormat": "{{f5_virtual_server_name}}"
    }
   ]
  },
  {
   "title": "Virtual Server Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(f5_virtual_server_clientside_bytes_in_total{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval])",
     "legendFormat": "{{f5_virtual_server_name}} - In"
    },
    {
     "expr": "-1 * rate(f5_virtual_server_clientside_bytes_out_total{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval])",
     "legendFormat": "{{f5_virtual_server_name}} - Out"
    }
   ]
  },
  {
   "title": "Virtual Server Packets Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(f5_virtual_server_packets_in_total{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval])",
     "legendFormat": "{{f5_virtual_server_name}} - In"
    },
    {
     "expr": "-1 * rate(f5_virtual_server_packets_out_total{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval])",
     "legendFormat": "{{f5_virtual_server_name}} - Out"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Virtual Server Concurrent Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "f5_virtual_server_clientside_connection_count{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}",
     "legendFormat": "{{f5_virtual_server_name}}"
    }
   ]
  },
  {
   "title": "Virtual Server Connection Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "C/s" } },
   "targets": [
    {
     "expr": "rate(f5_virtual_server_clientside_connection_total{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval])",
     "legendFormat": "{{f5_virtual_server_name}}"
    }
   ]
  },
  {
   "title": "Virtual Server Avg. Connection Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "f5_virtual_server_clientside_connection_duration_mean_milliseconds{job=\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}",
     "legendFormat": "{{f5_virtual_server_name}}"
    }
   ]
  }
 ]
}