{
 "title": "LTM - HTTP Profile",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(f5_system_info, environment)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "device_name",
    "query": {
     "query": "label_values(f5_system_state_up_ratio{environment=~\"$environment\"},job)"
    }
   },
   {
    "name": "profile_name",
    "query": {
     "query": "label_values(f5_profile_http_info,f5_profile_http_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Profile Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Profile Settings",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "f5_profile_http_info{environment=~\"$environment\", job=\"$device_name\", f5_profile_http_name=~\"$profile_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "changes(f5_profile_http_generation{environment=~\"$environment\", job=\"$device_name\", f5_profile_http_name=~\"$profile_name\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP Request / Response", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(f5_profile_http_requests_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_http_name=~\"$profile_name\"}[$__rate_interval])",
     "legendFormat": "{{f5_profile_http_name}}"
    }
   ]
  },
  {
   "title": "HTTP Response Rate By Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(f5_profile_http_responses_by_status_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_http_name=~\"$profile_name\"}[$__rate_interval])",
     "legendFormat": "{{f5_profile_http_name}}: {{http_status_range}}"
    }
   ]
  },
  {
   "title": "HTTP Requests By Version [1h]",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(f5_profile_http_requests_by_version_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_http_name=~\"$profile_name\"}[1h])",
     "legendFormat": "{{f5_profile_http_name}} - {{http_version}}"
    }
   ]
  },
  {
   "title": "HTTP Requests By Method",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(f5_profile_http_requests_by_method_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_http_name=~\"$profile_name\"}[1h])",
     "legendFormat": "{{f5_profile_http_name}} - {{http_method}}"
    }
   ]
  },
  {
   "title": "HTTP Responses By Version [1h]",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(f5_profile_http_responses_by_version_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_http_name=~\"$profile_name\"}[1h])",
     "legendFormat": "{{f5_profile_http_name}} - {{http_version}}"
    }
   ]
  },
  {
   "title": "Virtual Server HTTP Request Response",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Virtual Server HTTP Request Rate By Method",
   "type": "timeseries",
   "description": "This panel requires data retrieved from a bash command. If the BigIP account used to scrape the device lacks this permission, it is expected to be blank.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(f5_virtual_server_profile_http_requests_by_method_total{environment=~\"$environment\", f5_profile_http_name=~\"$profile_name\", job=\"$device_name\"}[$__rate_interval])",
     "legendFormat": "{{f5_profile_http_name}}: {{http_method}}"
    }
   ]
  },
  {
   "title": "Virtual Server HTTP Response Rate By Status",
   "type": "timeseries",
   "description": "This panel requires data retrieved from a bash command. If the BigIP account used to scrape the device lacks this permission, it is expected to be blank.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(f5_virtual_server_profile_http_responses_by_status_total{environment=~\"$environment\", f5_profile_http_name=~\"$profile_name\", job=\"$device_name\"}[$__rate_interval])",
     "legendFormat": "{{f5_profile_http_name}}: {{http_status_range}}"
    }
   ]
  }
 ]
}