{
 "title": "LTM - DNS Profile",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(f5_system_info, environment)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "device_name",
    "query": {
     "query": "label_values(f5_profile_dns_info{environment=~\"$environment\"},job)"
    }
   },
   {
    "name": "profile_name",
    "query": {
     "query": "label_values(f5_profile_dns_info,f5_profile_dns_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Enable DNS Metrics",
   "type": "text",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "DNS Metrics are not enabled in the Opentelemtry Collector by default\n(due to the relatively large number of requests required to gather the data).\n\n\nFor data to populate in this dashboard, you need to enable them as follows (and then you might want\nto delete this panel):\n\n## Enable For All BigIPs\nYou can enable GTM metrics for all BigIPs by editing the\nconfig/ast_defaults.yaml file in the AST directory and setting\n\n```yaml\nbigip_receiver_defaults:\n...\n  data_types:\n...\n    f5.dns:\n      enabled: true\n```\n\n## Enable For Select BigIPs\nYou can enable DNS metrics for specific BigIPs by editing the\nconfig/bigip_receivers.yaml file and setting the flag for the\nspecific devices you need:\n\n```yaml\nbigip/1:\n  endpoint: https://10.0.0.1\n  data_types:\n    f5.dns:\n      enabled: true\n```"
   }
  },
  { "title": "Profile Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Profile Settings",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "f5_profile_dns_info{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "changes(f5_profile_dns_generation{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Profile Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(f5_profile_dns_request_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
     "legendFormat": "{{f5_profile_dns_name}}"
    }
   ]
  },
  {
   "title": "DNS Profile Response Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(f5_profile_dns_response_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
     "legendFormat": "{{f5_profile_dns_name}}"
    }
   ]
  },
  {
   "title": "DNS Request / Response Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS EDNS Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_edns_request_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}}"
      }
     ]
    },
    {
     "title": "DNS EDNS Response Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_response_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}}"
      }
     ]
    },
    {
     "title": "DNS Request By Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_request_by_type_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}}: {{f5_profile_dns_request_type}}"
      }
     ]
    },
    {
     "title": "DNS Response By Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_response_by_type_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}}: {{f5_profile_dns_response_type}}"
      }
     ]
    },
    {
     "title": "DNS Response By Return Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_response_by_return_code_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}}: {{f5_profile_dns_return_code_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS Zone NS Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries by type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_dnsx_query_type_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}} : {{f5_profile_dns_dnsx_qtype}}"
      },
      {
       "expr": "rate(f5_profile_dns_axfr_queries_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}} : AXFR"
      },
      {
       "expr": "rate(f5_profile_dns_ixfr_queries_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}} : IXFR"
      }
     ]
    },
    {
     "title": "XFR Notify Rates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_xfr_notifies_sent_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}}"
      }
     ]
    },
    {
     "title": "DNSX Query Rates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_dnsx_queries_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}}"
      }
     ]
    },
    {
     "title": "DNSX Response Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_dnsx_responses_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS Resolver Cache Hit / Miss Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client Cache Hits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_client_hits_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}}"
      }
     ]
    },
    {
     "title": "Client Cache Misses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_client_misses_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}}"
      }
     ]
    },
    {
     "title": "Client Hits Response Time",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "f5_profile_dns_client_hits_response_time_milliseconds{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Client Misses Response Time",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "f5_profile_dns_client_misses_response_time_milliseconds{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS Resolver Cache Traffic Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS Profile Bit Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_bits_in_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}} - In"
      },
      {
       "expr": "-1 * rate(f5_profile_dns_bits_out_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}} - Out"
      }
     ]
    },
    {
     "title": "TCP Bit Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_tcp_bits_in_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}} - In"
      },
      {
       "expr": "-1 * rate(f5_profile_dns_tcp_bits_out_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}} - Out"
      }
     ]
    },
    {
     "title": "Packet Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_packets_in_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}} - In"
      },
      {
       "expr": "-1 * rate(f5_profile_dns_packets_out_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}} - Out"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS Resolver Cache Message Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message Hit Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_msg_hits_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}}"
      }
     ]
    },
    {
     "title": "Message Miss Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_msg_misses_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}}"
      }
     ]
    },
    {
     "title": "Message Eviction Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_msg_evictions_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}}"
      }
     ]
    },
    {
     "title": "Message Modification Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_msg_modifications_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS Resolver Server Query Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Query Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_server_queries_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}}"
      }
     ]
    },
    {
     "title": "Server Response Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_server_responses_total{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "{{f5_profile_dns_name}}"
      }
     ]
    },
    {
     "title": "Server Queries",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "rate(f5_profile_dns_server_queries_rate_requests_per_second{environment=~\"$environment\", job=\"$device_name\", f5_profile_dns_name=~\"$profile_name\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}