{
 "title": "BigIP Receiver Stats",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "log_datasource", "label": "Clickhouse", "query": "grafana-clickhouse-datasource" },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "endpoint",
    "label": "API Endpoint",
    "query": {
     "query": "label_values(endpoint_scrape_requests_total,endpoint)"
    }
   },
   {
    "name": "device_name",
    "label": "Device",
    "query": {
     "query": "label_values(scrape_duration_seconds{job=~\"bigip.*\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Collector Container Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT Timestamp as \"timestamp\", concat(Body, ' ', LogAttributes) as \"body\", SeverityText as \"level\", TraceId as \"traceID\", mapConcat(LogAttributes, ResourceAttributes) AS labels FROM \"otel\".\"otel_logs\" WHERE ( timestamp >= $__fromTime AND timestamp <= $__toTime ) ORDER BY timestamp DESC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Full Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=~\"bigip.*\", job=~\"$device_name\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Endpoint Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "endpoint_scrape_duration_seconds{path=~\"$endpoint\", job=~\"$device_name\"}",
     "legendFormat": "{{job}} {{path}}"
    }
   ]
  },
  {
   "title": "Status Per Endpoint",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(sum_over_time(endpoint_scrape_responses_total{path=~\"$endpoint\", job=~\"$device_name\"}[1h])) by (status_code, job, path) / on(job, path) group_left() sum(sum_over_time(endpoint_scrape_responses_total{path=~\"$endpoint\", job=~\"$device_name\"}[1h])) by (job, path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Responses Rate By Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(endpoint_scrape_responses_total{path=~\"$endpoint\", job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Response Size Bytes (by endpoint)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_scrape_response_size_bytes{path=~\"$endpoint\", job=~\"$device_name\"}",
     "legendFormat": "{{job}} {{path}}"
    }
   ]
  },
  {
   "title": "API Requests By Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by(path, job) (rate(endpoint_scrape_requests_total{path=~\"$endpoint\", job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}}: {{path}}"
    }
   ]
  }
 ]
}