apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: grafana
    spec:
      securityContext:
          runAsUser: 472
          fsGroup: 472
      containers:
        - env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: GF_SECURITY_ADMIN_PASSWORD
                  name: env
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                configMapKeyRef:
                  key: GF_SECURITY_ADMIN_USER
                  name: env
            - name: SENSOR_ID
              valueFrom:
                configMapKeyRef:
                  key: SENSOR_ID
                  name: env
            - name: SENSOR_SECRET_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: SENSOR_SECRET_TOKEN
                  name: env
          image: grafana/grafana:11.2.0
          name: grafana
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana
            - mountPath: /etc/grafana/provisioning/datasources
              name: datasources-conf
            - mountPath: /etc/grafana/provisioning/dashboards
              name: dashboards-conf
            - mountPath: /etc/grafana/provisioning/dashboards/bigip/device
              name: bigip-device-conf
            - mountPath: /etc/grafana/provisioning/dashboards/bigip/fleet
              name: bigip-fleet-conf
            - mountPath: /etc/grafana/provisioning/dashboards/bigip/profile
              name: bigip-profile-conf
            - mountPath: /etc/grafana/provisioning/dashboards/otel-collector
              name: otel-collector-conf
      restartPolicy: Always
      volumes:
        - name: grafana
          persistentVolumeClaim:
            claimName: grafana
        - name: datasources-conf
          configMap:
            name: datasources-config
        - name: dashboards-conf
          configMap:
            name: dashboards-config
        - name: bigip-device-conf
          configMap:
            name: bigip-device-config
        - name: bigip-fleet-conf
          configMap:
            name: bigip-fleet-config
        - name: bigip-profile-conf
          configMap:
            name: bigip-profile-config
        - name: otel-collector-conf
          configMap:
            name: otel-collector-config
