apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.ast.service: otel-collector
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: otel-collector
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.ast.service: otel-collector
    spec:
      securityContext:
          runAsUser: 0
      containers:
        - args:
            - --config=/etc/otel-collector-config/defaults/bigip-scraper-config.yaml
          volumeMounts:
          - name: scraper-config
            mountPath: "/etc/otel-collector-config/defaults/"
          - name: rec-pipe-config
            mountPath: "/etc/otel-collector-config/"

          env:
            - name: BIGIP_PASSWORD_1
              valueFrom:
                configMapKeyRef:
                  key: BIGIP_PASSWORD_1
                  name: env-device-secrets
            - name: BIGIP_PASSWORD_2
              valueFrom:
                configMapKeyRef:
                  key: BIGIP_PASSWORD_2
                  name: env-device-secrets
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: GF_SECURITY_ADMIN_PASSWORD
                  name: env
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                configMapKeyRef:
                  key: GF_SECURITY_ADMIN_USER
                  name: env
            - name: SENSOR_ID
              valueFrom:
                configMapKeyRef:
                  key: SENSOR_ID
                  name: env
            - name: SENSOR_SECRET_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: SENSOR_SECRET_TOKEN
                  name: env
          image: ghcr.io/f5devcentral/application-study-tool/otel_custom_collector:v0.9.3
          name: otel-collector
      restartPolicy: Always
      volumes:
      - name: scraper-config
        configMap:
          name: bigip-scraper-config
      - name: rec-pipe-config
        configMap:
          name: receivers-pipeline-config
