apiVersion: v1
data:
  prometheus.yml: |-
    global:
      scrape_interval: 1m

    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 1m
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'otel-collector'
        scrape_interval: 30s
        static_configs:
          - targets: ['otel-collector:8888']
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
