apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.ast.service: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.ast.service: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.ast.service: prometheus
    spec:
      securityContext:
          runAsUser: 472
          fsGroup: 472
      containers:
        - args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --web.console.templates=/etc/prometheus/consoles
            - --web.enable-lifecycle
            - --enable-feature=otlp-write-receiver
            - --storage.tsdb.retention.time=1y
          image: prom/prometheus:v2.54.1
          name: prometheus
          ports:
            - containerPort: 9090
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/prometheus/prometheus.yml
              name: prometheus-cm0
              subPath: prometheus.yml
            - mountPath: /prometheus
              name: prometheus
      restartPolicy: Always
      terminationGracePeriodSeconds: 300
      volumes:
        - configMap:
            items:
              - key: prometheus.yml
                path: prometheus.yml
            name: prometheus-cm0
          name: prometheus-cm0
        - name: prometheus
          persistentVolumeClaim:
            claimName: prometheus
