apiVersion: v1
data:
  receivers.yaml: |
    bigip/1:
      collection_interval: 60s
      data_types:
        f5.apm:
          enabled: false
        f5.cgnat:
          enabled: false
        f5.dns:
          enabled: false
        f5.dos:
          enabled: false
        f5.firewall:
          enabled: false
        f5.gtm:
          enabled: false
        f5.policy.api_protection:
          enabled: false
        f5.policy.asm:
          enabled: false
        f5.policy.firewall:
          enabled: false
        f5.policy.ip_intelligence:
          enabled: false
        f5.policy.nat:
          enabled: false
        f5.profile.dos:
          enabled: false
      endpoint: https://[BIG-IP IP ADDRESS]
      password: ${env:BIGIP_PASSWORD_1}
      timeout: 60s
      tls:
        ca_file: ''
        insecure_skip_verify: true
      username: admin
  pipelines.yaml: |
    metrics/local:
      exporters:
      - otlphttp/metrics-local
      - debug/bigip
      processors:
      - batch/local
      receivers:
      - bigip/1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: receivers-pipeline-config
