global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'otel-collector'
    scrape_interval: 30s
    static_configs:
      - targets: ['otel-collector:8888']
  - job_name: 'grafana'
    scrape_interval: 30s
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'clickhouse'
    scrape_interval: 30s
    static_configs:
      - targets: ['clickhouse:9126']