apiVersion: v1
data:
  datasources.yaml: |-
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus:9090
        basicAuth: false
        isDefault: true
        editable: true
        jsonData:
          timeInterval: 60s
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: datasources-config
