apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.ast.service: prometheus
  name: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
