{
 "title": "DoS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(f5_system_info, environment)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "device_name",
    "label": "Device",
    "query": {
     "query": "label_values(f5_dos_attacks_total{environment=~\"$environment\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Enabling DoS Metrics",
   "type": "text",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "DoS Metrics are not enabled in the Opentelemtry Collector by default\n(due to the relatively large number of requests required to gather the data).\n\n\nFor data to populate in this dashboard, you need to enable them as follows (and then you might want\nto delete this panel):\n\n## Enable For All BigIPs\nYou can enable DoS metrics for all BigIPs by editing the\nconfig/ast_defaults.yaml file in the AST directory and setting\n\n```yaml\nbigip_receiver_defaults:\n...\n  data_types:\n...\n    f5.dos:\n      enabled: true\n```\n\n## Enable For Select BigIPs\nYou can enable DoS metrics for specific BigIPs by editing the\nconfig/bigip_receivers.yaml file and setting the flag for the\nspecific devices you need:\n\n```yaml\nbigip/1:\n  endpoint: https://10.0.0.1\n  data_types:\n    f5.dos:\n      enabled: true\n```"
   }
  },
  {
   "title": "DoS Profile Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "f5_profile_dos_info{environment=~\"$environment\", job=~\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DoS Stats Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(job) (rate(f5_dos_stats_total{environment=~\"$environment\", job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DoS Attacks Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "sum by(job) (rate(f5_dos_attacks_total{environment=~\"$environment\", job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DoS Drops Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "sum by(job) (rate(f5_dos_drops_total{environment=~\"$environment\", job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DoS Stats By Vector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by(f5_dos_vector_name) (rate(f5_dos_stats_total{environment=~\"$environment\", job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DoS Attacks By Vector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "sum by(f5_dos_vector_name) (rate(f5_dos_attacks_total{environment=~\"$environment\", job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DoS Drops By Vector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "sum by(f5_dos_vector_name) (rate(f5_dos_drops_total{environment=~\"$environment\", job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DoS BA Stats Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by(job) (rate(f5_dos_ba_stats_total{environment=~\"$environment\", job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DoS BA Detected Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "sum by(job) (rate(f5_dos_ba_detected_total{environment=~\"$environment\", job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DoS BA Drops Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "expr": "sum by(job) (rate(f5_dos_ba_drops_total{environment=~\"$environment\", job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DoS BD Stats Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum by(job) (rate(f5_dos_bd_stats_total{environment=~\"$environment\", job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DoS BD Detected Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "targets": [
    {
     "expr": "sum by(job) (rate(f5_dos_bd_detected_total{environment=~\"$environment\", job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DoS BD Drops Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "targets": [
    {
     "expr": "sum by(job) (rate(f5_dos_bd_drops_total{environment=~\"$environment\", job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DoS Bytes Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(f5_dos_bytes_total{environment=~\"$environment\", job=~\"$device_name\"}[$__rate_interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DoS Byte Drop Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(f5_dos_bytes_drops_total{environment=~\"$environment\", job=~\"$device_name\"}[$__rate_interval]))  by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}