{
 "title": "Device Utilization",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(f5_system_info, environment)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "device_name",
    "label": "Device",
    "query": {
     "query": "label_values(f5_system_state_up_ratio{environment=~\"$environment\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg. CPU Utilization ",
   "type": "timeseries",
   "description": "Avg Utilization Across All CPUs",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(job) (f5_system_cpu_utilization_ratio{environment=~\"$environment\", job=~\"$device_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. Mem Utilization ",
   "type": "timeseries",
   "description": "Avg System Memory Used",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(job) (f5_system_memory_used_bytes{environment=~\"$environment\", job=~\"$device_name\", state=\"used\"}) / avg by(job) (f5_system_memory_total_bytes{environment=~\"$environment\", job=~\"$device_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(f5_system_logical_disk_usage_bytes{environment=~\"$environment\", job=~\"$device_name\", state=~\"free\"} * 1000000) by (job, f5_system_logical_disk_name) /sum(f5_system_logical_disk_limit_bytes{environment=~\"$environment\", job=~\"$device_name\"}) by(job, f5_system_logical_disk_name)",
     "legendFormat": "{{job}} ({{f5_system_logical_disk_name}})"
    }
   ]
  },
  { "title": "Configuration Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Configured Virtual Servers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by(job) (f5_virtual_server_info{environment=~\"$environment\", job=~\"$device_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Configured Pools",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "count by(job) (f5_pool_info{environment=~\"$environment\", job=~\"$device_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Configured Pool Members",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "count by(job) (sum by(job, f5_pool_member_name) (f5_pool_member_enabled_ratio{environment=~\"$environment\", job=~\"$device_name\"}))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Aggregate Virtual Server Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Current Client Side Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(job) (f5_virtual_server_clientside_connection_count{environment=~\"$environment\", job=~\"$device_name\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Client Side Data Rate In/Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8*sum by(job) (rate(f5_virtual_server_clientside_bytes_in_total{environment=~\"$environment\", job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}} - In"
    },
    {
     "expr": "-8*sum by(job) (rate(f5_virtual_server_clientside_bytes_out_total{environment=~\"$environment\", job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}} - Out"
    }
   ]
  }
 ]
}