{
 "title": "Virtual Servers",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(f5_system_info, environment)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "virtual_server",
    "label": "Virtual Server",
    "query": {
     "query": "label_values(f5_virtual_server_info,f5_virtual_server_name)"
    }
   },
   {
    "name": "device_name",
    "label": "Device",
    "query": {
     "query": "label_values(f5_virtual_server_info{environment=~\"$environment\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Virtual Server Availability [24h]",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum_over_time(f5_virtual_server_availability_ratio{environment=~\"$environment\", job=~\"$device_name\", availability_state=\"available\", f5_virtual_server_name=~\"$virtual_server\"}[24h]) / count_over_time(f5_virtual_server_availability_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"available\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(f5_virtual_server_availability_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"offline\"}[24h]) / count_over_time(f5_virtual_server_availability_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"offline\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(f5_virtual_server_availability_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"unknown\"}[24h]) / count_over_time(f5_virtual_server_availability_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"unknown\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(f5_virtual_server_enabled_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[24h]) / count_over_time(f5_virtual_server_enabled_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VS isAvailable",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "f5_virtual_server_availability_ratio{environment=~\"$environment\", job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"available\"}",
     "legendFormat": "{{job}} {{ f5_virtual_server_name }}"
    }
   ]
  },
  {
   "title": "VS Connection Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(f5_virtual_server_clientside_connection_total{environment=~\"$environment\", f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval])",
     "legendFormat": "{{job}} {{f5_virtual_server_name}}"
    }
   ]
  },
  {
   "title": "VS Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * rate(f5_virtual_server_clientside_bytes_in_total{environment=~\"$environment\", f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval])",
     "legendFormat": "{{job}} {{f5_virtual_server_name}} - In"
    },
    {
     "expr": "-8 * rate(f5_virtual_server_clientside_bytes_out_total{environment=~\"$environment\", f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval])",
     "legendFormat": "{{job}} {{f5_virtual_server_name}} - Out"
    }
   ]
  },
  {
   "title": "Fleet Virtual Server Details",
   "type": "table",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "f5_virtual_server_info{environment=~\"$environment\", f5_virtual_server_name=~\"$virtual_server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "changes(f5_virtual_server_generation{environment=~\"$environment\", f5_virtual_server_name=~\"$virtual_server\", job=~\"$device_name\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}