{
 "title": "CGNAT",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(f5_system_info, environment)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "device_name",
    "label": "Device",
    "query": {
     "query": "label_values(f5_cgnat_lsn_pool_generation{environment=~\"$environment\"},job)"
    }
   },
   {
    "name": "pool",
    "label": "LSN Pool",
    "query": {
     "query": "label_values(f5_cgnat_lsn_pool_generation{job=~\"$device_name\"},f5_pool_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Enabling CGNAT Metrics",
   "type": "text",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "CGNAT Metrics are not enabled in the Opentelemtry Collector by default\n(due to the relatively large number of requests required to gather the data).\n\n\nFor data to populate in this dashboard, you need to enable them as follows (and then you might want\nto delete this panel):\n\n## Enable For All BigIPs\nYou can enable CGNAT metrics for all BigIPs by editing the\nconfig/ast_defaults.yaml file in the AST directory and setting\n\n```yaml\nbigip_receiver_defaults:\n...\n  data_types:\n...\n    f5.cgnat:\n      enabled: true\n```\n\n## Enable For Select BigIPs\nYou can enable CGNAT metrics for specific BigIPs by editing the\nconfig/bigip_receivers.yaml file and setting the flag for the\nspecific devices you need:\n\n```yaml\nbigip/1:\n  endpoint: https://10.0.0.1\n  data_types:\n    f5.cgnat:\n      enabled: true\n```"
   }
  },
  {
   "title": "LSN Pool Settings",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "f5_cgnat_lsn_pool_pba_info{environment=~\"$environment\", job=~\"$device_name\", f5_pool_name=~\"$pool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool Translations (Current)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "f5_cgnat_lsn_pool_translations_current{environment=~\"$environment\", job=~\"$device_name\", f5_pool_name=~\"$pool\"}",
     "legendFormat": "{{job}} - {{f5_pool_name}}"
    }
   ]
  },
  {
   "title": "PBA Active Port Blocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "f5_cgnat_lsn_pool_pba_port_blocks_active{environment=~\"$environment\", job=~\"$device_name\", f5_pool_name=~\"$pool\"}",
     "legendFormat": "{{job}} - {{f5_pool_name}}"
    }
   ]
  },
  {
   "title": "Pool Translation Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(f5_cgnat_lsn_pool_translations_requests_total{environment=~\"$environment\", job=~\"$device_name\", f5_pool_name=~\"$pool\"}[$__rate_interval])",
     "legendFormat": "{{job}} - {{f5_pool_name}}"
    }
   ]
  },
  {
   "title": "PBA Port Block Allocation Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(f5_cgnat_lsn_pool_pba_port_blocks_allocations_total{environment=~\"$environment\", job=~\"$device_name\", f5_pool_name=~\"$pool\"}[$__rate_interval])",
     "legendFormat": "{{job}} - {{f5_pool_name}}"
    }
   ]
  },
  {
   "title": "Pool Translation Request Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(f5_cgnat_lsn_pool_translations_requests_total{environment=~\"$environment\", job=~\"$device_name\", f5_pool_name=~\"$pool\"}[$__rate_interval])",
     "legendFormat": "{{job}} - {{f5_pool_name}}"
    }
   ]
  },
  {
   "title": "PBA Port Block Allocation Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "rate(f5_cgnat_lsn_pool_pba_port_blocks_allocation_failures_total{environment=~\"$environment\", job=~\"$device_name\", f5_pool_name=~\"$pool\"}[$__rate_interval])",
     "legendFormat": "{{job}} - {{f5_pool_name}}"
    }
   ]
  }
 ]
}