{
 "title": "APM Sessions",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(f5_system_info, environment)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "device_name",
    "label": "Device",
    "query": {
     "query": "label_values(f5_apm_sessions_current{environment=~\"$environment\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Enabling APM Metrics",
   "type": "text",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "APM Metrics are not enabled in the OpenTelemetry Collector by default\n(due to the relatively large number of requests required to gather the data).\n\n\nFor data to populate in this dashboard, you need to enable them as follows (and then you might want\nto delete this panel):\n\n## Enable For All BigIPs\nYou can enable APM metrics for all BigIPs by editing the\nconfig/ast_defaults.yaml file in the AST directory and setting\n\n```yaml\nbigip_receiver_defaults:\n...\n  data_types:\n...\n    f5.apm:\n      enabled: true\n```\n\n## Enable For Select BigIPs\nYou can enable APM metrics for specific BigIPs by editing the\nconfig/bigip_receivers.yaml file and setting the flag for the\nspecific devices you need:\n\n```yaml\nbigip/1:\n  endpoint: https://10.0.0.1\n  data_types:\n    f5.apm:\n      enabled: true\n```"
   }
  },
  {
   "title": "Current APM Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "f5_apm_sessions_current{environment=~\"$environment\", job=~\"$device_name\"}",
     "legendFormat": "{{job}} - {{f5_apm_session_type}}"
    }
   ]
  },
  {
   "title": "APM Session Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "f5_apm_sessions_current{environment=~\"$environment\", job=~\"$device_name\"} / f5_apm_sessions_limit{environment=~\"$environment\", job=~\"$device_name\"}",
     "legendFormat": "{{job}} - {{f5_apm_session_type}}"
    }
   ]
  },
  {
   "title": "Current APM Access Sessions By State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "f5_apm_access_sessions_current{environment=~\"$environment\", job=~\"$device_name\"}",
     "legendFormat": "{{job}} - {{f5_apm_session_state}}"
    }
   ]
  },
  {
   "title": "APM Access Sessions Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(f5_apm_access_sessions_current{environment=~\"$environment\", job=~\"$device_name\"}) by (job) / sum(f5_apm_access_sessions_limit{environment=~\"$environment\", job=~\"$device_name\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}