{
 "title": "Fleet Inventory",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(f5_system_info, environment)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Inventory Total By Software Version",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(f5_system_info{environment=~\"$environment\"}) by (system_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inventory Total By Product Name",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(f5_system_info{environment=~\"$environment\"}) by (system_product_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inventory Total By Product Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(f5_system_info{environment=~\"$environment\"}) by (f5_system_marketing_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Inventory By Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(f5_system_info{environment=~\"$environment\"})  by (system_version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Module Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "f5_module_provision_generation{environment=~\"$environment\", level!=\"none\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inventory Detail",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "f5_system_info{environment=~\"$environment\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "f5_system_failover_peer_active_state_ratio{environment=~\"$environment\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}