{
 "title": "SSL Certificate Status",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(f5_system_info, environment)"
    }
   },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": {
    "content": "# SSL Certificate Status\n\nThis dashboard displays information about SSL Certificates associated with a BigIP Device.\nData collected includes (only) the following:\n\n* Certificate Name\n* Certificate Expiration Time\n* Certificate Key Type\n* Whether the certificate is part of a bundle"
   }
  },
  {
   "title": "Certificate Type",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(f5_ssl_certificate_expires_at{environment=~\"$environment\"}) by (key_type)",
     "legendFormat": "{{key_type}}"
    }
   ]
  },
  {
   "title": "Expires < 30 Days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(f5_ssl_certificate_expires_at{environment=~\"$environment\"} - time() < 86400 * 30)",
     "legendFormat": "{{key_type}}"
    }
   ]
  },
  {
   "title": "Expires < 90 Days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(f5_ssl_certificate_expires_at{environment=~\"$environment\"} - time() < 86400 * 90)",
     "legendFormat": "{{key_type}}"
    }
   ]
  },
  {
   "title": "Expires < 180 Days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(f5_ssl_certificate_expires_at{environment=~\"$environment\"} -time() < 86400 * 180)",
     "legendFormat": "{{key_type}}"
    }
   ]
  },
  { "title": "Certificate Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Certificates",
   "type": "table",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort(f5_ssl_certificate_expires_at{environment=~\"$environment\"}) - time()",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}