apiVersion: 1

datasources:
- name: ClickHouse
  type: grafana-clickhouse-datasource
  jsonData:
    defaultDatabase: otel
    port: 9000
    server: clickhouse
    username: grafana
    tlsSkipVerify: true
    logs:
      defaultDatabase: otel
      defaultTable: otel_logs
      otelEnabled: true
      otelVersion: 1.2.9
      timeColumn: Timestamp
      levelColumn: SeverityText
      messageColumn: Body
      selectContextColumns: false
    traces:
      defaultDatabase: otel
      defaultTable: otel_traces
      otelEnabled: true
      otelVersion: 1.2.9
      durationUnit: nanoseconds
      traceIdColumn: TraceId
      spanIdColumn: SpanId
      
      operationNameColumn: SpanName
      parentSpanIdColumn: ParentSpanId
      serviceNameColumn: ServiceName
      durationColumn: Duration
      startTimeColumn: Timestamp
      tagsColumn: SpanAttributes
      serviceTagsColumn: ResourceAttributes
      eventsColumnPrefix: Events
  secureJsonData:
    password: $GRAFANA_CLICKHOUSE_PASSWORD
    # tlsCACert:     <string> # TLS CA certificate
    # tlsClientCert: <string> # TLS client certificate
    # tlsClientKey:  <string> # TLS client key
