{
 "title": "SSLO Pipeline Summary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "log_datasource", "label": "Clickhouse", "query": "grafana-clickhouse-datasource" },
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "SSLO Logging System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clickhouse Service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"clickhouse\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Otel Service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"otel-collector\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accumulated Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) from \"otel\".\"sslo_logs\" as Value"
    }
   ]
  },
  { "title": "System State Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"log-analyzer\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum by(job) (rate(otelcol_process_cpu_seconds_total{job=\"otel-collector\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_OSCPUVirtualTimeMicroseconds[5m])/1000000",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_MemoryResident{job=\"clickhouse\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum by(job) (otelcol_process_runtime_total_sys_memory_bytes{job=\"otel-collector\"})",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"log-analyzer\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Incoming Syslog Messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(receiver) (rate(otelcol_receiver_accepted_log_records_total{receiver=\"syslog/sslo_logs_tcp\"}[$__rate_interval]))",
     "legendFormat": "Accepted"
    },
    {
     "expr": "sum by(receiver) (rate(otelcol_receiver_refused_log_records_total{receiver=\"syslog/sslo_logs_tcp\"}[$__rate_interval]))",
     "legendFormat": "Refused"
    }
   ]
  },
  {
   "title": "Outgoing Otel Logs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(exporter) (rate(otelcol_exporter_sent_log_records_total{exporter=\"clickhouse/sslo_logs\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum by(exporter) (rate(otelcol_exporter_send_failed_log_records_total{exporter=\"clickhouse/sslo_logs\"}[$__rate_interval]))",
     "legendFormat": "Failed"
    }
   ]
  }
 ]
}