apiVersion: v1
kind: Service
metadata:
  name: graf-lb-service
spec:
  selector:
    io.kompose.service: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  clusterIP: 10.0.171.239
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
---
apiVersion: v1
kind: Service
metadata:
  name: prom-lb-service
spec:
  selector:
    io.kompose.service: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  clusterIP: 10.0.171.239
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
