name: Push Image to ghcr.io
run-name: ${{ github.actor }} is running this workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    #tags:
    #  - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  Pull-From_Gitlab:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
      - name: Login to GitLab
        uses: docker/login-action@v3
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}
      - name: Set variables
        run: |
          VER=$(cat COLLECTOR_VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Pull Gitlab Image
        run: docker pull registry.gitlab.com/f5/greenhouse/apps/seven-layer-cake-collector/otel_custom_collector:${{ env.VERSION }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to Github
        run:
          |
            exit_code=0
            docker pull ghcr.io/f5networks/f5-insight-for-bigip/otel_custom_collector:${{ env.VERSION }} > /dev/null 2>&1 || exit_code=$?
            if [ $exit_code -eq 0 ]; then
                 echo "Image already exists in the github registry, skipping push"
                 exit 0
            fi
            docker tag registry.gitlab.com/f5/greenhouse/apps/seven-layer-cake-collector/otel_custom_collector:${{ env.VERSION }} ghcr.io/f5networks/f5-insight-for-bigip/otel_custom_collector:${{ env.VERSION }}
            docker tag registry.gitlab.com/f5/greenhouse/apps/seven-layer-cake-collector/otel_custom_collector:${{ env.VERSION }} ghcr.io/f5networks/f5-insight-for-bigip/otel_custom_collector:latest
            docker push ghcr.io/f5networks/f5-insight-for-bigip/otel_custom_collector:${{ env.VERSION }}
            docker push ghcr.io/f5networks/f5-insight-for-bigip/otel_custom_collector:latest
